### ISSUE TITLE
Have incoming clients download assets that are missing.

### ISSUE THREAD

**Issue by drwhut** [drwhut/tabletop-club#11]
**Is your feature request related to a problem? Please describe.**
Right now, if a client connects to the server, and the client does not have the asset that another player has spawned, then the client will very likely error.

**Describe the solution you'd like**
If the client has an asset that the host does not have, have the host send the asset to the client and saved into the `user://assets` folder, then the client would import the file like it would at startup.

**Describe alternatives you've considered**
Trust that the client has the necessary assets.

**Additional context**
If not done properly, this could be the source of many security issues. This is why I have added the *help wanted* label.

**Comment by drwhut** [comment]
After having a few discussions, I have decided to go the route of "before the assets are downloaded, ask the user first if they want to download them, but warn them that what they are downloading is user-generated content".

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
Is it possible for the player to join without downloading the asset and just replace with a default one, if the player choose to not download it?

**Comment by drwhut** [comment]
Yeah, if you choose not to download the assets, the idea is the game should try it's best to build the piece up without the missing asset (e.g. if you're missing a texture, it'll just be untextured).
