### ISSUE TITLE
Feature: Mouse over actions

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#112]
**Is your feature request related to a problem? Please describe.**
Many actions can only be performed by picking them up

**Describe the solution you'd like**
When hovering over any objects, following actions should be possible to do without picking up the object:
- Rotate
- Reset rotate
- Flip
- Shuffle
- Lifting height

This might be a bit tricky since we also have selected objects.

**Describe alternatives you've considered**
None

**Comment by drwhut** [comment]
> > But I think there's something to be said about not allowing certain actions to be done on an object without first taking "control" of the object, i.e. hovering it. That being said, there is the Transform menu, but by design the player can't use it "instantly" - my concern is that if a shortcut would be assigned, then the player could potentially spam it.
> 
> Can you elaborate on that? I'm not aware how this can be abused

For example, the player holding down or mashing the shortcut to flip an object.

> The benefit here is: you don't have to pick it up - the game should make sure that when you flip it it lands on the exact same spot again. If you pick it up, flip it, you manually have to make sure to place it on the correct location again.

Ah, that's a really good point! I'll definitely consider adding buttons to the transform menu, but I think if shortcuts are going to be added, I'll need to make sure the system cannot be abused.

**Comment by elmodor** [comment]
> For example, the player holding down or mashing the shortcut to flip an object.

Well, only allow one action to be executed? So if flip is being made, another flip has to wait until it is finished.
But even without this restriction, why do you think this is abusing it (mashing the shortcut to flip an object)?. What is the abuse exactly? I can just flip the table to delete the object if I want to ruin the fun.
Did you mean to quickly "peak" at the card? How's that any different than picking up the card and mashing the flip button?

> but I think if shortcuts are going to be added, I'll need to make sure the system cannot be abused.

I hope there will be a way :smile:

**Comment by elmodor** [comment]
Physics is fun! (more or less)

Let's say a card has two states: NO_ANIMATION, ANIMATION_RUNNING
Player starts the flipping, state changes to: ANIMATION_RUNNING
Cards is done flipping, physics done changes states to: NO_ANIMATION

Now you can do different things while ANIMATION_RUNNING and another flip is triggered:
- Prevent the action until state is in NO_ANIMATION 
- Using a timeout for an action
- Freeze physics, immediately set the transformation/rotation to the end state, unfreeze physics and begin the new action from there
- Stop the current animation and begin the new animation from the current state

I agree tho that the fun should not be ruin by wonky physics. 
Accessibility on the other hand is very important too. Sometimes you play virtual tabletop games with people who are not very familiar with computers - and there I think shortcuts (F for flip for example) are easy to remember and to execute. When they have to pick up stuff or find some button in a menu - it gets complicated. So you can say: just press F

**Comment by drwhut** [comment]
While that would work, I think that solution might be more complicated than it needs to be.

There's not really any "animations" in the game, as much as it is the physics engine manipulating stuff. So since this is for objects that are not hovering, this would have to involve creating a whole new sub-system for the game (unless the game would temporarily hover something to flip it, but that seems kinda tacky).

Since there's already a system in place for instantly changing the transform of an object through the UI, I'm more inclined to take advantage of that system, rather than create a whole new one.

> Accessibility on the other hand is very important too.

That's very true! Actually your example raises a question: do you think the player should need to select objects first before flipping them, or should they be able to flip objects as long as they are hovering over them?

**Comment by elmodor** [comment]
> Since there's already a system in place for instantly changing the transform of an object through the UI, I'm more inclined to take advantage of that system, rather than create a whole new one.

Sounds right. I'm not yet that familiar with GD

> Do you think the player should need to select objects first before flipping them, or should they be able to flip objects as long as they are hovering over them?

Well initially I thought about just hovering. But how do you differentiate when an action should be applied to the selected or to the object being hovered over?

I took a peek into the "popular" tabletop sim. They apply a flip action on all selected and the object being hovered over.
