### ISSUE TITLE
Feature: Rotate keyboard shortcut

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#113]
**Is your feature request related to a problem? Please describe.**
Rotating an objects only works with the scrollwheel

**Describe the solution you'd like**
The "reset rotation" button (R) could be changed to also rotate the object. So I basically want to press R and the object should rotate by the selected degree. Maybe add a different shortcut to reset rotation?

**Describe alternatives you've considered**
None

**Comment by drwhut** [comment]
Yeah, this makes sense - my initial thoughts were that maybe the arrow keys would be better suited for this, e.g. pressing the left arrow key would rotate the object anti-clockwise. Thoughts?

**Comment by elmodor** [comment]
I'm not an expert on shortcut ergonomics. It does make sense.

But when playing you usually have your hands: one on WASD the other on the mouse. So moving one to the arrow keys just for rotating ...
How about: rotating via R, reset rotation by holding R?
Or: keybindings can be changed. But we would need an option for keybindings to trigger when "holding" a key?

**Comment by drwhut** [comment]
Interesting - I never considered holding down the key to do something different. I'll have a look into how to detect that! But I'm not sure if it's possible in Godot to assign an event based on "holding" something, so if this is the method we implement, it would have to be the same key.

**Comment by elmodor** [comment]
I was looking into it briefly and I don't think having different actions for pressing and holding is a good idea. 
To detect a "hold" you have to wait a bit - and during that time you can not activate the "press" action. So in the end the "press" action will be delayed.
I think it's better to use a different key or this.

I will propose a MR to which adds a keybinding to rotate a piece.
