### ISSUE TITLE
Bug: ERROR thrown when card back_face is empty

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#118]
**Describe the bug**
When the config of a card does not have a back_face set or back_face is set to "" an error is thrown when launching the game.  
```
ERROR: Key 'texture_path_1' not found in entry!
   at: call (modules/gdscript/gdscript_functions.cpp:774)
ERROR: Cannot add entry to AssetDB, entry is invalid!
   at: call (modules/gdscript/gdscript_functions.cpp:774)
```

Also the card is then missing and you can not select it when spawning objects

**To Reproduce**
1. edit a card config.cfg
2. Add `back_face=""` to `[*]`
3. Launch the game
4. Error is logged to console

**Expected behavior**
back_face="" is a valid configuration and should not result in an error

**Environment**
Arch Linux

**Version**
v0.1.0 Beta 1

**Comment by elmodor** [comment]
The issue here is that `AssetDB.gd` appends `texture_path_1` for cards to `expected_keys` and checks the hash to be equal and every key to be there. It would require some sort of `optional_keys` list but then we probably can't compare the hash anymore.

**Comment by drwhut** [comment]
My fix for this was going to be allowing `texture_path_1` to be empty, and if that was the case, just using a blank texture for the 2nd material.
