### ISSUE TITLE
README has no screenshots or videos of tabletop-club in action

### ISSUE THREAD

**Issue by csells** [drwhut/tabletop-club#135]
**Which page(s) in the documentation should be changed?**
- https://github.com/drwhut/tabletop-club#readme
- https://tabletop-club.readthedocs.io/en/latest/

**What should be changed?**
The docs should have inspirational screenshots and videos of tabletop-club in action, otherwise I, as a potential user and contributor, have no idea what's possible.

**Why do you think the change is needed?**
The current wall of text README and docs doesn't make me want to use or contribute to tabletop-club.

**Comment by drwhut** [comment]
I'll probably add some of the screenshots from [the itch.io page](https://drwhut.itch.io/tabletop-club) to both the README and the docs when I get the chance.
