### ISSUE TITLE
Feature: Draw hidden from container

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#137]
**Is your feature request related to a problem? Please describe.**
Sometimes you need to draw objects from a bag that should be hidden / not visible to anyone else. Currently this is not possible because the orientation of the object being drawn from a container has the same orientation as the container itself.

**Describe the solution you'd like**
One of:
- An option to set to orientation of objects when they are drawn from the container
- A checkbox on a container "Draw flipped" so that objects being drawn are already flipped

**Describe alternatives you've considered**
You can put the container upside down, but this counts as shaking the container and items drop out of the container ...

**Comment by drwhut** [comment]
One possible workaround is to place a hidden area around the container.

But it could be useful to, for cards at least, for them to default to orient down I think.

**Comment by elmodor** [comment]
I had the issue with a token tbh.

If it would be possible to have a toggle for this on the container - that would be the best option I think.

Another possibility would be if the container remembers the orientation of the token/card being put in. So if the card is being put inside facing downwards it will be drawn like this too.

In my opinion a toggle on the container would be sufficient enough tho.

**Comment by drwhut** [comment]
> Another possibility would be if the container remembers the orientation of the token/card being put in. So if the card is being put inside facing downwards it will be drawn like this too.

I think I prefer this method to be honest. This way, a player wouldn't need to know beforehand that there was an option in the context menu, and this is (in my opinion) intuitive. It shouldn't be too difficult to implement either.
