### ISSUE TITLE
Allow assets to have configurable values.

### ISSUE THREAD

**Issue by drwhut** [drwhut/tabletop-club#14]
**Is your feature request related to a problem? Please describe.**
Right now sorting a stack only sorts it alphabetically based on the file name, which is pointless for most applications.

**Describe the solution you'd like**
Allow in the configuration files in the assets folder to give certain assets values (either raw values e.g. a poker chip with 10 on its face would have the value `10` or have assets contain a dictionary of values, e.g. `value=6, suit="H"`). This way, users can sort stacks of these assets by either their raw value or a type of value.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by SeanKuehl** [comment]
Hey Drwhut, I was looking at the code around this and I was thinking I might be able to help with this. I think since ConfigFile.get_value(...) returns variant type that if we wanted to we can make the value a array([ ]) or a dictionary({ }). I was wondering though, if the only purpose for this value would be to sort, then wouldn't there only need to be one value?(I may not entirely understand the "sort by type of value")

**Comment by drwhut** [comment]
The idea behind the different values is so that you can sort by more than one thing - an example being playing cards, which have two values: a suit and it's number/face. Then in the context menu when you have a stack of those items, it would have a "Sort by" button that would display the different types of values, or just a "Sort by value" button if it's just the one value.

**Comment by SeanKuehl** [comment]
Ok, thanks for clearing that up. I think this idea of having different values for sorting might be suited well by a dictionary where the keys are the user-entered names of the values we can use in the menus and the values are what will be used to sort the assets (i.e. "suit": "H" or "Mana": 0). I was looking around and found the code for adding values to an asset from the config file in AssetDB.gd but I was just wondering where the code for the context menu and sorting is? Also would these only apply to Cards and Tokens or do you think they'd be useful on other things as well like Pieces? I might be able to start on the code in the next few days.

**Comment by drwhut** [comment]
The context menu code is in `CameraController.gd`, and the code for the sorting is in `Stack.gd`. Yeah, I think this would only apply to cards and tokens, as they're the only objects that can stack in the game, and as such, they can have an order.

**Comment by SeanKuehl** [comment]
Thanks, I was thinking of adding one single kind of sort that would sort the stack based on the custom values. I will have to build in a check in case not all cards/tokens in the stack have the same custom values. Do you think one kind of sort based on the custom values will be enough or do you think there should be more with more options?

**Comment by drwhut** [comment]
That's a good point - the thought I had was that you could select what you wanted to sort by (e.g. either sort by value or by suit for playing cards), but then if for example, you sort by suit, how does it sort the cards within the suits? By their value? Randomly?

As you've mentioned, there are two possible avenues we could go down:
* Have just one sort button that, no matter how many custom values the cards/tokens have, it will sort them (for example, with playing cards it could sort by suits, then by values? But then what determines the order the values get sorted in?).
* Have multiple sort buttons for each value type, and the game will try its best to sort items that have the same value (again, what order would the other values be sorted in?).

Personally, I think the more options the better, so I would opt for the second one.

**Comment by SeanKuehl** [comment]
Only thing I'm wondering is how many buttons should we have/allow for how many options? If we have custom values X,Y and Z we can sort by should we have a button to sort for each of them individually, all of them together and all of the combinations? (Sort by X and Y, sort by Y and Z etc.) Ultimately we want to give the most customization to the user while at the same time making it streamlined and easy for them, I'm just not sure what the best way is to go about this.

**Comment by drwhut** [comment]
Ideally, I would imagine there is one sort button for every custom value (for example, the context menu could have a "Sort >" button, which brings up a sub-menu with all the available sort options), which still leaves the problem of how we inter-sort objects.

I don't think there is one "right answer" for how we deal with more than two custom values (if there are two custom values, that's simple enough, as you just inter-sort with the custom value that wasn't the one that was initially selected), so I think just for the sake of having something to work with (and potentially improve upon in the future if needs be), I'd say just inter-sort the other custom values by alphabetical order of their keys. So for example, say some objects have values X, Y, and Z, and the player wants to sort the stack by Y. The game would then sort the objects in the order: Y, X, Z.

If you can think of any other ideas, let me know, but I think this is the most sensible solution for now.

**Comment by SeanKuehl** [comment]
One thing I can think of, keeping your idea of a dropdown menu with all the custom values is allow the user to do the combinations. Something like they can tap on a bunch of the values and then press a sort button. If they only want to sort by Y, then they press Y and then sort but if they want to sort things Y,Z,X they press the buttons in that order and press sort. The prototype I make will probably be really simple and I'll change it into whatever we end up deciding on.

**Comment by drwhut** [comment]
That's a good idea, but honestly, I think we might be overthinking it a little bit - most players won't really care about how a stack is sorted, as long as it *is* sorted. I think having one button to sort by each custom value, and then having the game automatically inter-sort if needs be, is good enough. If it ends up being the case that we need a more involved sorting system, then I can always open up a separate issue for it.

**Comment by SeanKuehl** [comment]
Hey, I'm looking in AssetDB.gd, function _import_asset  but I can't find anything for tokens. I found something for cards, but tokens seem to only be mentioned. Any help would be appreciated.

**Comment by drwhut** [comment]
We'll want this functionality for both cards and tokens, so you'll probably need an if statement with the `or` operator for both types of objects.

Pieces is the in-code definition for 3D objects that have physics in the game. Stackable pieces (Cards + Tokens) are a subset of pieces that can stack on top of one another (what this issue is concerned with).
