### ISSUE TITLE
Bug: Config star wildcard problem

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#146]
**Describe the bug**
Wildcards seem not to work all the time:
card names:
`my_card_f.png` front
`my_card_b.png' back

config:
```
[my_card_f.png]
desc = "My Card"
back_face = "my_card_b.png"

[*_b]
ignore = true

[*_b.png]
ignore = true
```
Both ignores do not work. AssetDB tries to load them and throws an error because no back_face is set for _b.png cards

**To Reproduce**
See above

**Expected behavior**
*_b.png cards are ignored and not loaded

**Version**
v0.1.0 Beta 1

**Comment by drwhut** [comment]
Fixed with the merging of #148.
