### ISSUE TITLE
[Feature Request] Add more game equipments

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#152]
Nice to see your project. I have been creating a list of tabletop games as well as a mod for Minetest. 
https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Tabletop-Games

Could you consider adding more equipments?

**Comment by elmodor** [comment]
I think there is already a list of planned pieces here:
#28 

If you want to see a specific game/piece it will probably be helpful if you can name them directly. Your list has a lot of different game modes. Are there any in particular that you would like to see?

**Comment by GrimPixel** [comment]
I saw that default equipments right after posting this. As far as I know, a lot of them are popular, including xiàngqí, shōgi, ganjifa, Jass, hanafuda. The designs of many of them are not protected by copyrights. I just can't find their SVG files.

I am having something different in my mind. Maybe I will create my own set of equipments, so that the default pack is not too large.

**Comment by GrimPixel** [comment]
SVG resources I have gathered that:

ajedrez:
-  https://commons.wikimedia.org/wiki/Category:SVG_chess_pieces
- https://commons.wikimedia.org/wiki/File:Chessboard480.svg
- https://commons.wikimedia.org/wiki/File:Hex_chessboard_for_3_players.svg
- https://commons.wikimedia.org/wiki/File:Hexagonal_chess_board.svg

baraja:
- https://commons.wikimedia.org/wiki/Category:Castilian_pattern

carte da gioco:
- https://commons.wikimedia.org/wiki/Category:Brescia_deck

domino:
- https://commons.wikimedia.org/wiki/File:Dominoes_double-9_set_black_background_white_dots.svg

hanafuda:
- https://commons.wikimedia.org/wiki/Category:Hanafuda

hmak ruk:
- https://commons.wikimedia.org/wiki/Category:Makruk_pieces
- https://commons.wikimedia.org/wiki/File:Makrukboard.svg

hwatu:
- https://commons.wikimedia.org/wiki/Category:Hwatu

janggi:
- https://commons.wikimedia.org/wiki/Category:Janggi_pieces
- https://github.com/Ka-hu/chess-pieces

máquè:
- https://commons.wikimedia.org/wiki/Category:SVG_Planar_illustrations_of_Mahjong_tiles
- https://commons.wikimedia.org/wiki/Category:SVG_Oblique_illustrations_of_Mahjong_tiles

shōgi:
- https://commons.wikimedia.org/wiki/Category:SVG_traditional_shogi_pieces
- https://commons.wikimedia.org/wiki/Category:SVG_traditional_shogi_pieces_(promoted)
- https://commons.wikimedia.org/wiki/File:Shogi_board.svg

sittuyin:
- https://github.com/Ka-hu/chess-pieces

xiàngqí:
- https://commons.wikimedia.org/wiki/Category:Xiangqi_pieces
- https://commons.wikimedia.org/wiki/File:Xiangqi_board.svg

xuānhépái:
- https://commons.wikimedia.org/wiki/Category:Pai_Gow_(narrow_SVG)

dice:
- https://commons.wikimedia.org/wiki/Category:Dice_faces

tokens:
- https://commons.wikimedia.org/wiki/Category:Casino_token_icons

**Comment by drwhut** [comment]
Everything that is planned to be added to the default asset pack is listed in #28, as all of the games on that list are in the public domain. But I'll keep this issue in mind for the links when looking for assets!
