### ISSUE TITLE
[ERROR] modules/gdscript/gdscript_functions.cpp:774 call: Piece stacks/{number} has an empty 'pieces' array!

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#163]
**Describe the bug**
[ERROR] modules/gdscript/gdscript_functions.cpp:774 call: Piece stacks/{number} has an empty 'pieces' array!

**To Reproduce**
1. Load “Poker”
2. Throw some tokens
3. Click on “Undo”

**Expected behavior**
Table is cleared.

**Screenshots**
![ksnip_20221203-180204](https://user-images.githubusercontent.com/39795763/205455257-80421e68-3a5a-4adf-a035-525e8da271fc.png)

**Environment**
Arch Linux

**Version**
v0.1.0 beta

**Comment by drwhut** [comment]
Note: to replicate the issue, one needs to throw tokens from a stack until only one token remains in the stack.
