### ISSUE TITLE
Extend the “Flip orientation” into “Row+”, “Row-”, “Pitch+”, “Pitch-”, “Yaw+”, “Yaw-”

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#165]
Some objects require flipping in 6 orientations, and the angle may be not exactly π. So 6 keys are required.
I find 123456 are good for this.

**Comment by drwhut** [comment]
I'm not sure if extra key bindings are needed when one can precisely rotate an object using the `Transform` menu when right-clicking an object. For the vast majority of cases, I think having one flip binding should be enough.

**Comment by GrimPixel** [comment]
The doubling dice of backgammon requires this, as well as cubes in boggle.
