### ISSUE TITLE
[Feature Request] Restrict camera view

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#167]
In some games like lùjūnqí, Stratego, gunjin shōgi, patterns on pieces are hidden from the opponent. So the camera in these games need to be restricted

**Comment by GrimPixel** [comment]
Those pieces are standing, and their patterns face the one who is supposed to see them.

**Comment by elmodor** [comment]
Ah, maybe also something like Codenames (https://boardgamegeek.com/image/2660376/codenames) or Mastermind.

**Comment by drwhut** [comment]
I'm gonna close this issue for now for the following reasons:

- In the majority of cases, hidden areas should solve this issue.
- For cases where the pieces still need to be seen by other players, but only a specific side, I think relying on player trust should suffice for now - one can even see if a player is rotating their camera by looking at their cursor.
- Even if this was implemented, there would 100% be ways to circumvent it, for example the new details button in the context menu, or by using the debug menu.
