### ISSUE TITLE
[Feature request] Add description for “45” near “Menu”

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#169]
It is unexplained what that number means.

**Comment by GrimPixel** [comment]
I think it could be sliders of degrees for “Row”, “Pitch”, “Yaw” on the right side of the screen, which can be controlled with the mouse wheel.

**Comment by drwhut** [comment]
> I think it could be sliders of degrees for “Row”, “Pitch”, “Yaw” on the right side of the screen, which can be controlled with the mouse wheel.

Think this should probably be a separate issue, as this is adding a new feature.
