### ISSUE TITLE
Add an option to make speakers non-spatial.

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#170]
It is not supposed to be placed at the centre of the table, so for everyone, the music is louder in one ear.

**Comment by elmodor** [comment]
I agree that the speaker as "background" music is a bit weird.

The speaker could have a toggle to use spatial sound or not. So for background music you would turn off spatial sound and it would be the same volume on all outputs.

**Comment by drwhut** [comment]
Yeah, I agree having a toggle on speakers to determine whether they are spatial or not would be a good quality-of-life addition.
