### ISSUE TITLE
Add “Tiles” similar to “Cards”

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#172]
In games like mahjong, tiles need to be stacked and aligned. It's not for mahjong solitaire, but mahjong proper.

**Comment by youkaicountry** [comment]
Cube tokens can be used for this purpose. The scale parameter can be used to set any 3d rectangular shape, each side can be textured, and they stack like cards.

**Comment by GrimPixel** [comment]
It feels strange to find them in “Tokens”, especially when tokens in Japanese mahjong are also there. Mahjong tiles need to be stacked both horizontally and vertically, and be able to shuffle across multiple stacks.

**Comment by drwhut** [comment]
As mentioned above, cube tokens are a better fit for mahjong tiles than cards are.

Placing the tiles next to each other on the table is a good workaround for not being able to stack them horizontally.
