### ISSUE TITLE
Allow other shapes for “Tokens”

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#173]
In Japanese Mahjong, tokens are sticks with patterns. In monopoly, they are rectangular.

**Comment by drwhut** [comment]
Having a look at the pieces you mentioned, the Mahjong tokens could easily be made with long and thin cube tokens in-game using the `scale` property.

Plus, we are somewhat limited in the shapes we can "stack". Implementing a way to stack generic shapes would be incredibly challenging.

**Comment by GrimPixel** [comment]
Similar to ganjifa, tokens can't be aligned in areas.
