### ISSUE TITLE
[Bug] Enlarged view of the last drawn card unavailable

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#178]
**Describe the bug**
The larger view (by mouse hovering) of the last drawn card is unavailable.

**To Reproduce**
1. Load “Poker”
2. Draw cards to “Player” area
3. Move cursor over the last drawn card
4. Its view doesn't show up

**Expected behavior**
Show the card's enlarged view.

**Environment**
Arch Linux

**Version**
v0.1.0 beta

**Comment by elmodor** [comment]
It seems the preview does not work on "selected" cards inside the players hand.

As a workaround: Clicking on the table should unselect them and then the preview should work again.

**Comment by GrimPixel** [comment]
OK, this is not a bug.

**Comment by elmodor** [comment]
I would say it is a bug and selected cards on hand should also be able to have the preview popup? no?
