### ISSUE TITLE
[Feature request] Display number of objects in a hidden area

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#179]
Players should have an idea how many cards/tiles left in one's hand, so he/she can't declare victory arbitrarily.
Maybe there is already a mechanism doing so in multiplayer, and I just don't know.

**Comment by drwhut** [comment]
I'm not sure if this is much of an issue - if someone wanted to declare victory prematurely, then they would still have to "prove" their victory by removing their hidden area, or taking the cards out of their hand.
