### ISSUE TITLE
[Feature request] Ambience

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#186]
Play multiple audio files as background music. They can be taken from websites like https://www.freesoundslibrary.com/

**Comment by elmodor** [comment]
I think you would be able to do this with the speakers once they have the option to play music non spatial - then these can be used as background music.

Hence, duplicate of #170

**Comment by elmodor** [comment]
Yeah, just use multiple speakers? You can scale them down too so they wont use as much space
