### ISSUE TITLE
Some confusions by “Vector3”

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#189]
In tabletop-club/assets/TabletopClub/cards/config.cfg, there is a `scale = Vector3(6.35, 1, 8.89)`. The y value should mean 1 cm, however, the card in game looks like 0.01 cm. If I create an object with height 1 cm and write 1 in y, would it be converted to 0.01 cm?

**Comment by elmodor** [comment]
The default card layout is (1, 0.01, 1).
So the scale factors you set in the config are multiplied by this value. If you want a card to be 1cm thick you would need to write 100 in Y - but I assume at that point you should use a token and not a card.

**Comment by GrimPixel** [comment]
Ah, thanks. In my opinion, this is an extra complexity. Typing 0.01 doesn't require much work for each asset.

**Comment by drwhut** [comment]
To be fair, cards were not really designed to be scaled in the y-axis. Maybe the `scale` property could be simplified to a `Vector2` for the X and Z axes? What do you think?

**Comment by elmodor** [comment]
> Maybe the scale property could be simplified to a Vector2 for the X and Z axes? What do you think?

Sounds good to me. Only expose to the config what should actually be changeable.

**Comment by GrimPixel** [comment]
In some games like dominoes and anagrams, tiles are not supposed to be so thin in y direction.

**Comment by drwhut** [comment]
> In some games like dominoes, anagrams, mahjong, tiles are not supposed to be so thin in y direction.

Cube tokens (which I think would be better suited for the objects you mentioned) would keep the `Vector3` scale. This is just for cards, where the thickness, by design, should stay the same.

**Comment by GrimPixel** [comment]
Per your words, even current French-suited cards can be created with cube tokens. So why don't just remove the “Cards” and create tokens only?

**Comment by drwhut** [comment]
One could do that, but cards are designed to have no thickness, whereas tokens can have thickness.

**Comment by GrimPixel** [comment]
Etymologically, “card” comes from Greek “χάρτης”, which means papyrus; “token” comes from Proto-Germanic “*taikną”, which means “symbol”.
In my opinion, “tile” is better than “token”. It comes from Latin “tegula”, which means the tile for building.
Currently, tokens do not behave like cards in hand.

**Comment by elmodor** [comment]
I will look into this.
What I would implement:
- Making the scale optionally a Vector2
- If scale is Vector2 apply a per-defined Y value based on type (for cards this would be `0.01`)
- Adjust the documentation, only using Vector2 for cards for now
