### ISSUE TITLE
Add an icon to distinguish stacks from individual objects.

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#190]
The card deck and the card at its top are not easily distinguishable. There could be a new object type “Decks”.

**Comment by GrimPixel** [comment]
Yes, there.

**Comment by drwhut** [comment]
It's definitely something to consider. Back when the project first started, pre-made stacks of cards and tokens were in their own category - maybe that should be the case again? Or maybe add two new categories: "Decks" for stacks of cards, and "Stacks" for stacks of tokens. Or maybe it's more intuitive to keep the stacks with the objects they're made of? Would like to get other people's opinion on this.

**Comment by GrimPixel** [comment]
An alternative way is to indicate stacks with a stack icon.

**Comment by elmodor** [comment]
Maybe there's a way to indicate stacks a bit better? Token stacks are clearly distinguishable but not so for cards. Maybe as GrimPixel said with an additional icon in the preview window?
Not sure if adding more categories helps. This will make it more tedious to switch categories if you are lookign for something?

**Comment by GrimPixel** [comment]
As for reducing categories, “Speakers”, “Timers”, “Containers” can be integrated into “Miscellany”.
