### ISSUE TITLE
“Quick grab” and “Stop grabbing” too quick to see

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#192]
After grabbing on the object, the texts in the lower-right corner changed rapidly, leaving no time to read “Quick grab” and “Stop grabbing”.

**Comment by elmodor** [comment]
I assume this was made to be able to "quick grab" from a stack. But I agree that there is no time to read this. I would just remove the whole block in `CameraController.gd`:
```
		elif _is_grabbing_selected:
			text += _set_control_hint_label_row(tr("Quick grab"), tr("Move Mouse"))
			text += _set_control_hint_label_row(tr("Stop grabbing"), lmb, release)
```
because there's no way to read this anyways.
