### ISSUE TITLE
[Feature request] Zoom in to and out from the cursor

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#196]
Just zoom in to and out from the cursor, so I don't need to press keys.

**Comment by elmodor** [comment]
How should the zoom in and out happen if you don't press anything?
Do you mean the camera? The object? When hovering? A preview?

Please try to be as specific as possible when describing the feature you want/need.

**Comment by GrimPixel** [comment]
Oh, I was unaware there are other “zoom in” and “zoom out”. I just found these two phrases on other programs, which mean to enlarge or narrow the view. Here it is the camera.

**Comment by drwhut** [comment]
If you mean the field of view, this can already be done via the options menu under "Video".

The way the camera currently zooms in and out is more natural and intuitive in my opinion.

**Comment by GrimPixel** [comment]
It is not the field of view. When we zoom in and zoom out on OpenStreetMap, the cursor's position determines where it zooms, instead of the centre of screen. It's like that.
