### ISSUE TITLE
[Feature request] Patterns for cards

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#197]
Each set of cards may have different patterns like Paris pattern, Vienna pattern, English pattern, etc. for French-suited playing cards.
PySolFC has many sets of low-quality patterns.
https://pysolfc.sourceforge.io/

**Comment by elmodor** [comment]
I guess this relates to #28 

Any other assets have to be created by the community and distributed differently (not through the official game release). See https://tabletop-club.readthedocs.io/en/latest/custom_assets/asset_packs/index.html
