### ISSUE TITLE
Hide the top, side, left bottom, right bottom elements automatically

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#200]
They are distractions and could be hidden when the cursor isn't near them.

**Comment by elmodor** [comment]
I don't quite understand what you mean. What elements are on the bottom right? Do you mean the tooltip? These can already be disabled in: Settings -> Controls -> Hide Control Hints

Or do you mean:
- Menu bar at the top
- Function icons at the left side

**Comment by drwhut** [comment]
All of the UI can be hidden by pressing F9. I'm not sure if it's necessary to automatically hide these elements when the cursor is not near them, since this is a simulator rather than an immersive experience.
