### ISSUE TITLE
Add list of resources related to tabletop games

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#201]
**Is your feature request related to a problem? Please describe.**
People don't know which related tools are helpful.

**Describe the solution you'd like**
Put up a list of resources.

**Describe alternatives you've considered**
Pin the topic of resources at the top of a forum, which is not present yet.

**Additional context**
https://cardcreatr.sffc.xyz/
https://yewtu.be/channel/UC5--Olk4nljSNeT5wXfTOuA

**Comment by drwhut** [comment]
I think these links would be better suited in a forum, like you mentioned, or the creator of an asset pack could provide a link to a resource explaining how to play the game it represents.
