### ISSUE TITLE
[Feature request] Shuffle across stacks

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#202]
**Is your feature request related to a problem? Please describe.**
In some games, shuffling needs to be done across stacks, e.g. mahjong.

**Describe the solution you'd like**
Shuffle across stacks.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by drwhut** [comment]
What do you mean by shuffling "across stacks"?

**Comment by GrimPixel** [comment]
If I select multiple stacks and click on “Shuffle”, then the cards are shuffled within the multiple stacks.

**Comment by drwhut** [comment]
As in, a card in stack A may or may not end up in stack B? Do the sizes of the stacks stay the same afterwards?

Could you provide an example (e.g. a video) of this happening in a game?

**Comment by GrimPixel** [comment]
A card in stack A may end up in stack B. The sizes of the stacks stay the same.
If someone creates a mahjong “Game”, then there will be 4 stacks and a player needs to select the 4 stacks and click on “Shuffle”.
https://yewtu.be/watch?v=uKMbNHaHcCY

**Comment by elmodor** [comment]
Sounds like something that is very niche and could be added via scripting? 
Not sure if a default "shuffle across stacks" is a good solution if you accidentally had multiple stacks selected and shuffle. You won't even notice that you shuffled them with each other.

**Comment by GrimPixel** [comment]
If they were accidentally shuffled, and you don't notice it, then it is nothing different with not shuffling it. It is replacing an unknown sequence with another unknown sequence.

**Comment by drwhut** [comment]
Gonna close this for now, as this is too specific to justify adding to the game in general.

**Comment by GrimPixel** [comment]
I have an idea for Mahjong, etc.: place them in a concealed container. That is another issue.

**Comment by drwhut** [comment]
How do you mean "spawning pieces from boards randomly"?

**Comment by GrimPixel** [comment]
It's the additional feature to the feature https://github.com/drwhut/tabletop-club/issues/229.
