### ISSUE TITLE
Have white pips for some dice

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#203]
**Is your feature request related to a problem? Please describe.**
Many dice have black pips, which are hard to recognise.

![ksnip_20221211-010203](https://user-images.githubusercontent.com/39795763/206881539-bde22eeb-6143-477e-a7a0-610f4b02e92b.png)

**Describe the solution you'd like**
Dice have white pips.

**Describe alternatives you've considered**
Remove those dice.

**Comment by elmodor** [comment]
I think the dice system should be changed. Currently the base dice are:
- Black dice with white pips (can't change colors)
- White dice with black pips (used with different colors)

What actually should be:
- White dice with white pips (change color accordingly)
- White dice with black pips (change color accordingly)
