### ISSUE TITLE
Connection to Vassal (server or by log files)

### ISSUE THREAD

**Issue by mdtrooper** [drwhut/tabletop-club#207]
[Vassal](https://vassalengine.org/) is a old free software board game engine.

It has a lot options to play with it, for example by vassal server or by files (you can send the current game with other players by email).

It could be a good idea to connect to Vassal or open logfiles.

**Comment by drwhut** [comment]
Hmm... this seems to be mostly for 2D, turn based games. This could maybe be done with scripting at some point? But I'm not sure if it makes sense to integrate it into the game, since the interface for these two games is fundamentally different.
