### ISSUE TITLE
Feature: Dice Face Value Names

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#209]
**Is your feature request related to a problem? Please describe.**
Now that #142 is implemented, one can set a dice to a specific value.
Some games have dice which are not numbered but have images or other non numeric values - some might even have the same number multiple times (e.g. a die with face values: 0, 1, 1, 1, 2, 3).
Currently the index is used as "name" which is not very customizable.

**Describe the solution you'd like**
To be able to set those dice (with images and multiple numbers) it would be good to give a face value a name. This name should then be displayed when changing the dice value (#142).
This allows to describe an image or have the same name for multiple faces.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by drwhut** [comment]
Closed as of v0.1.3! :partying_face:
