### ISSUE TITLE
Change the default font to include more characters.

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#212]
**Is your feature request related to a problem? Please describe.**
The default font doesn't cover much of the Unicode including “ǔ”.

**Describe the solution you'd like**
Add an option to customise font. Maybe change the default font as well.

**Comment by drwhut** [comment]
I think having an option to change the font would be biting more than we could chew - I've never seen a game have this option.

However, I agree more characters should be supported by the default font - if a language contains characters that are not of Latin origin, then the plan would be to add a new font that does support those characters (e.g. Cyrillic characters use a different font when playing the game in Russian), but the example you gave is "u" with an accent, which in my opinion should be supported by the default font.

**Comment by GrimPixel** [comment]
There is only one font that covers most of the Unicode: [GNU Unifont](https://unifoundry.com/unifont/index.html). There will always be some characters left if any font is chosen.
An example of a game that can use custom font is Minetest.

**Comment by drwhut** [comment]
We don't necessarily need to cover *every* Unicode character, only those that are used by the languages that are added to the game.

**Comment by GrimPixel** [comment]
Does this mean there will be no support for languages that the fonts of the game don't cover?

**Comment by drwhut** [comment]
No, fonts will be added to the game when necessary, so for example, if the game had been translated to Japanese, then a font supporting Japanese characters will be added so the game is playable in that language.

**Comment by GrimPixel** [comment]
Is it possible to use system font when a glyph is missing in the font?

**Comment by drwhut** [comment]
Only in Godot 4.0 it looks like (see godotengine/godot#62973) - although even with this, I'd be concerned about the licenses of system fonts. I would be more comfortable using only open-license fonts.

**Comment by GrimPixel** [comment]
Ha, you will not be distributing system fonts. No need to worry.

**Comment by Fussmatte** [comment]
I'm gonna second the notion to change the font to have more characters. As it is, the current font for Latin-script languages has pretty poor support for Latin Extended-B.

Any Latin-script languages that rely on this block, like Polish, Esperanto, Czech, Turkish, Welsh, etc are either only partially represented, or not represented at all, so will look pretty ugly with fallback characters in-game:
![image](https://user-images.githubusercontent.com/44736084/213926777-e191f72c-383d-482f-8a5a-47314e84893a.png)

What's truly odd about this, though, is while the game uses the font "Cabin", it seems to be a stripped-down version. The version on the font's [official repo](https://github.com/impallari/Cabin) _does_ feature these characters. In that case, it would hopefully be trivial to bring the game's version up to par with the official one, to better future-proof for additional translations, and provide a better experience for international players who may use the chat feature.
