### ISSUE TITLE
First time of importing assets takes much time

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#213]
**Describe the bug**
When a custom asset is loaded for the first time, it takes a long time.

**Comment by drwhut** [comment]
Unfortunately this cannot be helped - in order for people to be able to add their own assets to the game without having to download the engine, it needs to use the editor's import system, which as you mentioned takes a while the first time something is imported.

The only other alternative would be to use GDScript functions to load specific file types - [a method exists for images](https://docs.godotengine.org/en/3.4/classes/class_image.html?highlight=image#class-image-method-load), but none exist for e.g. 3D models. I vaguely remember there being a discussion about adding a function for loading glTF files, but that would mean giving up support for OBJ and DAE files.
