### ISSUE TITLE
Change UV mapping for cubes and cylinders

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#215]
**Is your feature request related to a problem? Please describe.**
The current UV mapping for cubes and cylinders require all faces on a single file. It leads to huge amount of additional work for creating mahjong tiles, domino tiles, ganjifa cards etc.

**Describe the solution you'd like**
Change UV mapping to supporting single files for single faces.

**Comment by drwhut** [comment]
Closing as this is a duplicate of #115.
