### ISSUE TITLE
Problem with long lists and long names in a list for assets

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#221]
**Describe the bug**
The lower entries can't be selected if a list is long enough; “>”, “>>”, “Apply” buttons will be displaced if a name on a list is long enough.

**To Reproduce**
1. Add enough lists with long names for assets
2. Open the “Object” menu

**Comment by drwhut** [comment]
Are you able to show a screenshot of this happening?

**Comment by GrimPixel** [comment]
The buttons are displaced:
![ksnip_20221231-143957](https://user-images.githubusercontent.com/39795763/210140465-b5285918-03db-4b35-b49b-3750d5a6b5c2.png)

For the long list of assets, the dropdown instantly disappears when I press the screenshot shortcut. The list suits full-screen mode and when I have upper and lower panels on Linux, the lowest ones are hard to click on.
