### ISSUE TITLE
Play online radio

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#222]
**Is your feature request related to a problem? Please describe.**
What if radio can be played in game?

**Describe the solution you'd like**
Play online radio in game. There is a https://www.radio-browser.info/, where information about stations are gathered.

**Comment by drwhut** [comment]
I'm not sure if this is worth the effort to implement - currently if players want to play music that isn't in one of the asset packs, then they can put it on in the background while playing the game. So this would just be adding another way to do something that players can already do.
