### ISSUE TITLE
Customize the room code

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#224]
**Is your feature request related to a problem? Please describe.**
Currently, it is composed by four Latin letters, allowing 456976 rooms, which may cause problems like Pokémon Sword and Shield.

**Describe the solution you'd like**
Be able to customise the room code.

**Comment by drwhut** [comment]
> which may cause problems like Pokémon Sword and Shield.

Can you elaborate on this?

**Comment by elmodor** [comment]
I think increasing the room code to like 8 or maybe more digits should also
be sufficient for now.

**Comment by drwhut** [comment]
I'm not sure if increasing the number of characters is necessary - there will probably never be a time where there is more than 400,000 rooms active at once, I'd even be surprised if 50 rooms is surpassed to be honest.

Plus, we also want to keep the room code as simple and as memorable as possible so it's not a hastle for people to join a room.

**Comment by GrimPixel** [comment]
Pokémon Swords and Shields used to have 4 digits for a room, so a lot of people sent their pokémon to the wrong people. Later it was changed to 8 digits.

Custom names are memorable. It is how Jitsi Meet does.

You can be confident on its popularity. It is the only open-source tabletop game, written in GDScript, so the open-source community will be glad to know it; it can be used for education as well, so teachers and parents will find its value as well; it doesn't need much system resources; Digital India has been going on, which also stimulates the digitalisation in other developing countries, bringing more players.

**Comment by drwhut** [comment]
Will close this issue for now, I'm still not convinced that the room codes need to go beyond 4 characters (but thank you for the kind words anyways, Grim!) - if problems start arising from the lack of characters, I can always up the amount in the following update.
