### ISSUE TITLE
Show information in the context menu of objects.

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#227]
**Is your feature request related to a problem? Please describe.**
If the player doesn't know about a card's name or description, he/she may try to find it in “Objects” and take some time. If the card information is available, then the time is saved.

**Describe the solution you'd like**
Add “See information” on the right-click menu of the selected card.

**Comment by drwhut** [comment]
I could see info being shown for all objects, as well as cards.

**Comment by drwhut** [comment]
That might be a bit too much in such a small space - I was thinking about having a submenu (called something like "Details"?) which when clicked, shows the information (possibly in a moveable window?)

**Comment by GrimPixel** [comment]
Yes. That makes sense.
