### ISSUE TITLE
Endgames

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#231]
**Is your feature request related to a problem? Please describe.**
Beginners needs practises.

**Describe the solution you'd like**
Endgames can be created and loaded.

**Comment by drwhut** [comment]
Is it ok if in future issues you give a lot more detail? I have no idea what you mean by 'endgames'. What is an 'endgame'? How would it help beginners?

**Comment by GrimPixel** [comment]
Oh, I searched that word and found mostly irrelevant results. Here is a relevant one:
https://simplifychess.com/chess/complete-endgame-guide.html

Endgames are similar to https://github.com/drwhut/tabletop-club/issues/229, but in another category.

**Comment by drwhut** [comment]
This is very specific towards Chess - one could very easily make save games for Chess endgames, however I'm not sure it's worth providing them out of the box when there are plenty of websites out there that help with endgame practice already (see [lichess.org](https://lichess.org/practice), an open-source online Chess engine with practice modes)
