### ISSUE TITLE
Abnormal brightness

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#234]
It sometimes has weird brightness after importing modified assets. Maybe that import is irrelevant.
![ksnip_20230201-051200](https://user-images.githubusercontent.com/39795763/215957255-e9bc7acd-df90-438b-ac3d-fd90e7e99910.png)

**Comment by drwhut** [comment]
Are you able to consistently replicate this behaviour? What assets were modified, and how?

**Comment by GrimPixel** [comment]
This is uncommon. I can't find the pattern to repeat it. I edited some images, and I don't know if that is related.

**Comment by drwhut** [comment]
Will close for now until someone can find a way to replicate this behaviour.

**Comment by GrimPixel** [comment]
Here it appears again after using my pack https://codeberg.org/GrimPixel/Tabletop-Club-Assets
![colours](https://github.com/drwhut/tabletop-club/assets/39795763/019c4efb-7d34-4c2f-8268-0ffa563cb365)

**Comment by drwhut** [comment]
Is it still inconsistent, or is it cropping up more reliably using your asset pack?

**Comment by GrimPixel** [comment]
It happened after I modified the pack and it happens rarely.

**Comment by GrimPixel** [comment]
It appears that a “Back” is missing, but didn't to show up in the log. After adding a “Back” for that asset pack, it returned normal.

**Comment by drwhut** [comment]
> It appears that a “Back” is missing, but didn't to show up in the log. After adding a “Back” for that asset pack, it returned normal.

Interesting, I'll experiment with removing the back of card faces and see if I face the same issue that way.

**Comment by drwhut** [comment]
Hmm... still not able to replicate the issue, both with a modified version of the default asset pack, and with your custom-made packs. Maybe this is some sort of rare graphics driver issue? If that is the case, then maybe updating the game to use Godot 3.5.3 will hopefully stop this issue from occurring. Aside from that, I have no idea what could be causing this.

**Comment by GrimPixel** [comment]
Good to know that you are trying. I guess that the problematic one was randomly choosen as the first among the falling objects.
I will try different ways to reproduce it.
