### ISSUE TITLE
Missing module in forked Godot

### ISSUE THREAD

**Issue by Banbury** [drwhut/tabletop-club#258]
**Describe the bug**
I have downloaded `window-editor.zip` from `https://github.com/drwhut/godot/releases/tag/3.4.5-tabletop-build1`. When running Tabletop Club in Godot I get the error message: 
```
This version of Godot does not include the Tabletop Club module, etc. 
```
No assets are loaded.

**To Reproduce**
* Download the Windows version of the patched Godot
* Open the tabletop-club project
* Run the project

**Expected behavior**
No error message should appear. The assets should be loaded.

**Environment**
Windows 7

**Version**
v0.1.0-beta4

**Comment by drwhut** [comment]
Apologies for that, I've just uploaded a new build which includes the custom module, which you can download [here](https://github.com/drwhut/godot/releases/tag/3.4.5-tabletop-build1-1)!
