### ISSUE TITLE
Omit latter parts of too-long values in config.cfg

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#292]
**Is your feature request related to a problem? Please describe.**
When a value like URL is too long, the tooltip will be too long, so other values will be out of the screen.

**Describe the solution you'd like**
Use ellipsis to shorten too-long values in config.cfg.

**Comment by drwhut** [comment]
Yeah this makes sense, considering the fact there is now a "Details..." menu one can access to get further information about an asset.
