### ISSUE TITLE
Use “cuboids”, “cylinders”, “figures” instead of “cards”, “tokens”, “pieces”

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#303]
**Is your feature request related to a problem? Please describe.**
The “cards”-“tokens”-“pieces” solution is about the usage.
With “cards”-“tokens”-“pieces”, there are confusions: tiles and tokens are both “tokens”, round cards and round pieces are “tokens”.

**Describe the solution you'd like**
Use the  “cuboids”-“cylinders”-“figures” solution, which is about physical shapes and makes no confusion on their usages.

**Comment by GrimPixel** [comment]
Maybe instead of `tokens/cylinder` and `token/cube`, simply `cylinders` and `cubes`. That “dice” number of faces can be defined in `config.cfg` as well. Then there is no need for subdirectories.

**Comment by drwhut** [comment]
Maybe - if we decide that a compatibility break is necessary at some point, I'll consider those changes, but for now I want to try and keep asset packs working across various versions.
