### ISSUE TITLE
Slide an object with mouse

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#306]
**Is your feature request related to a problem? Please describe.**
There are some games where objects need to be slided, like 15-puzzle and klotski.

**Describe the solution you'd like**
Add an optional behaviour of sliding an object with mouse.

**Comment by drwhut** [comment]
Could you give detailed examples of why in these games these objects need to be slid, rather than grabbed and re-positioned? Would the flick tool be a suitable workaround in these instances?

**Comment by GrimPixel** [comment]
When playing these games, the blocks inside the frames are not supposed to be moved out of the frames.
https://www.youtube.com/watch?v=yCxhqQs_u3g

**Comment by GrimPixel** [comment]
Setting the lift height is working. I think it's the solution. I just don't have a frame model and blocks with fillets to test if everything works well.
