### ISSUE TITLE
Discord server invite broken

### ISSUE THREAD

**Issue by niltok64** [drwhut/tabletop-club#320]
**Describe the bug**
When I click on the Discord server link in the README, it opens the link and then Discord tells me that the link is invalid.

**To Reproduce**
1. Go to the README
2. Click on the invite link
3. See error

**Comment by niltok64** [comment]
sorry i know this is really really minor but i didnt know how else to address the problem so :/

**Comment by drwhut** [comment]
Hey, thank you for bringing this to my attention - I just tried using the link myself, but for me it appears to be fine?

![discord_ok](https://github.com/user-attachments/assets/84d6cfde-7e9f-4d05-8761-1e36e31fa063)

Can you post a screenshot for the error you get? Maybe try using different devices or browsers?

**Comment by niltok64** [comment]
oh shi i tried it again just now and it works, nevermind then

thank you anyways

**Comment by niltok64** [comment]
oh wait nevermind now its giving me this type of error
![image](https://github.com/user-attachments/assets/601cdbef-1ae6-4936-afed-5b382e979502)

**Comment by niltok64** [comment]
wait sorry it works now!!!

what i did is i just went into the discord app, then added the server through the little plus button, and now im in the server!

whoopsie!
