### ISSUE TITLE
Design a logo and icon.

### ISSUE THREAD

**Issue by drwhut** [drwhut/tabletop-club#38]
**Is your feature request related to a problem? Please describe.**
Right now the game has no logo, and it just uses the default Godot icon.

**Describe the solution you'd like**
I would like to create a logo and icon for the game, but I have no idea where to even start - I need ideas and inspiration for both assets!

Ideally, both assets should:
* Be able to be made as vector images.
* Be easily recognizable.
* Represent the fact that the game is a tabletop board game simulator.
* Give the game a cozy, relaxing, welcoming feel.

**Describe alternatives you've considered**
None.

**Additional context**
Any and all ideas, whether they be in the form of words or drawings, are welcome!

**Comment by gnrosa** [comment]
Hello, 
It is open for logo proposal ?

**Comment by drwhut** [comment]
Yes! If you've got an idea for the logo, please share it and I'll happily consider it :+1:

**Comment by gnrosa** [comment]
Here some ideas.

The first is an app logo suggestion.

![opentabletop_alt_logo_500_500](https://user-images.githubusercontent.com/40033972/108782982-5987c880-754b-11eb-909b-02c8e003f9ca.png)

The second is a suggestion for use in favicon or some other place where the text of the first is not readable 

![opentabletop_logo_500_500](https://user-images.githubusercontent.com/40033972/108782983-5a205f00-754b-11eb-826b-553110b5c892.png)

Variants

![opentabletop_alt_logo_500_500_bw](https://user-images.githubusercontent.com/40033972/108785274-da48c380-754f-11eb-94be-72570854543b.png)
![opentabletop_alt_logo_500_500_wb](https://user-images.githubusercontent.com/40033972/108785276-dae15a00-754f-11eb-9e15-a9b873e8184a.png)
![opentabletop_logo_500_500_bw](https://user-images.githubusercontent.com/40033972/108785278-db79f080-754f-11eb-9317-692ce9530b27.png)
![opentabletop_logo_500_500_wb](https://user-images.githubusercontent.com/40033972/108785280-db79f080-754f-11eb-8be2-a2dfc05419bc.png)

**Comment by gnrosa** [comment]
Main logo suggestion

![opentabletop_logo_500_500](https://user-images.githubusercontent.com/40033972/108785526-5e9b4680-7550-11eb-9c26-b6e60f3d6b0c.png)

Secondary logo suggestion
![opentabletop_alt_logo_500_500](https://user-images.githubusercontent.com/40033972/108785568-72df4380-7550-11eb-9b7a-d56b85e9d9d1.png)

Variants
![opentabletop_mono](https://user-images.githubusercontent.com/40033972/108785591-7d014200-7550-11eb-84ef-0dafd8e89e64.png)

**Comment by drwhut** [comment]
Thank you so much, I really appreciate it! :smile: I've just got a few questions/requests:
* I love the four hearts design, but I think having one of every suit would be more representative of the game. Can you make another variant where, instead of four hearts, there's one of every suit (so one spade, one heart, one club and one diamond)?
* Do you have these logos as vector images? No worries if not, it would just be more convenient to resize them.
* Do you know what license these logos would be under? If not, I'd recommend the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license (Anyone can share and adapt your work, but they *must* credit you, and they can only redistribute it under the same license).

**Comment by gnrosa** [comment]
Yes, I can do it, I will send it soon.
Thanks for the license tip.
The design is vectorized, made with inkscape.
What about the colors?

**Comment by drwhut** [comment]
Great! If it's ok with you, are you able to share the Inkscape files? I think the colours are great as they are - I love how the green makes it look like a poker table.

**Comment by gnrosa** [comment]
Logo Proposal V2
License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)
Original file type: [Inkscape](https://inkscape.org/) SVG
Download [here](https://drive.google.com/file/d/1EeTA7o8RTt4Mida6yqPT5zt88CcTd7QA/view?usp=sharing)

Font: [Bungee](https://fonts.google.com/specimen/Bungee)

Logo (With App Name)
![rect902](https://user-images.githubusercontent.com/40033972/108906639-deccb500-75ff-11eb-918e-42d2d7e6a7d7.png)

Logo (Without App Name)
![rect1070](https://user-images.githubusercontent.com/40033972/108906711-f015c180-75ff-11eb-9c93-2e3911c85933.png)

Color Scheme (RGB)
![path1183](https://user-images.githubusercontent.com/40033972/108906739-f99f2980-75ff-11eb-9272-62523bc40af2.png)

I'm learning to work with open source projects, if I'm doing something wrong, feel free to tell me.

**Comment by drwhut** [comment]
You're doing great! You've given me all the info I need (plus the font and colour scheme), which is fantastic. Can't wait to see the variants :+1:

P.S. Just in case you haven't seen it I've sent a request for the original file on Drive.

**Comment by gnrosa** [comment]
Access allowed 👍

**Comment by drwhut** [comment]
Thank you! Are you also able to send the Inkscape file for the second version you made?

**Comment by drwhut** [comment]
@gnrosa Hey! I've been discussing your logo proposal with friends, and we've come up with some simple tweaks that we think could make the logo almost perfect. Of course, you are under no obligation to do anything more, you've already contributed so much to the project! But I would be really appreciative if you were able to try these couple of changes:
* What if you took the suits from the second version, but arranged them in the same way you arranged the hearts in the first version? (So having one of each suit where they are the same colour as in the second version, each pointing a different direction, where they are all flat)
* Taking the first idea further, what if instead of having the suits be their respective colours, similar to the first version, the suits were coloured green?

**Comment by traverseda** [comment]
Give me access to the inkscape file and I'll make the changes. <myusername>@gmail.com

**Comment by drwhut** [comment]
Looks like the user who submitted the original proposal has since deleted their account :(

I don't have access to the second vector file they made (the one with the different suits), but [I did save the first](https://drive.google.com/file/d/1MaBh49FdxFgnGc19KVttAkBCZfiObUlu/view?usp=sharing) if you want to play around with it!

**Comment by traverseda** [comment]
![rect843](https://user-images.githubusercontent.com/2125828/152361308-e1ba6126-0d6a-40db-9ac4-0bed70fd8375.png)

That about right?

**Comment by drwhut** [comment]
Yeah, that's starting to look good! I just have a few points/suggestions:

* The name of the project changed from "Open Tabletop" to "Tabletop Club" due to a naming conflict last year - would it be possible to change the lettering on the vector image?
* How would the symbols look if they were black and red? Or if they were in coloured circles like in the previous proposal?
* I tried to download the SVG directly, but something's corrupted when I download it. I think you may have to upload it elsewhere...

**Comment by traverseda** [comment]
![logo1_large](https://user-images.githubusercontent.com/2125828/152545957-9883ef0e-6773-4e40-8b9d-fd993cf68d92.png)
![logo1_large-alt1](https://user-images.githubusercontent.com/2125828/152545961-c4080d2f-da63-4f11-a83d-41b31fcfb77a.png)
![logo1_large-alt2](https://user-images.githubusercontent.com/2125828/152545965-c9618a7a-c15c-45c9-a50e-4230ea773462.png)

Once you're happy with the results I can do a pull request and add them to this repo

**Comment by traverseda** [comment]
https://files.outsidecontext.solutions/s/G6aHm9qGPbJzBBH

Here are the in-progress files. The font is "bungee".

**Comment by drwhut** [comment]
Those proposals look good! Thank you for taking the time to edit them :)

No need to make a pull request, I've already got a plan to add the logo/icon to the game. I'll be sure to credit you and our ghost friend :)

**Comment by traverseda** [comment]
Well I'm just hopeful this is something I'll someday be able to use to play Catan with my friends. It's pretty far outside of my skillset though. Let me know if you need any django web apps developed :p

**Comment by leogott** [comment]
Concept
![TabletopClub Icon export](https://user-images.githubusercontent.com/61663141/158109879-5187174a-4b15-405c-aedc-a6bba287c16c.svg)

**Comment by leogott** [comment]
Improved Icon with prettier outlines:
![Icon new export](https://user-images.githubusercontent.com/61663141/158941273-0bb07fd5-e94c-4c60-b629-e55b4d7b7e7e.svg)
Mockup Splash:
![Splash new export](https://user-images.githubusercontent.com/61663141/158941281-c33cb77e-c3d4-4b61-99a6-378215af8bbf.svg)

Fonts used are _QTDublinIrish_ for the Q (would redraw by hand ideally, no idea about the license)
and _CelticHand_ for the Title (Pretty sure it has a free license).
An official godotengine Icon was used as well.

In case I loose interest: My work so far on these files is CC-BY 2.0

**Comment by traverseda** [comment]
Serif fonts in logos always look weird to me...

I think I see what you were trying to do with aligning the P along the cut through the middle, but I don't quite think it worked. I mean it's always going to be subjective, but I'd play with the font and alignment on the title to try and get a better result.

**Comment by leogott** [comment]
> Serif fonts in logos always look weird to me...

I just really disliked how _Bungee_ looked, when I used it there and picked a more playing-card-y font.
Something like this would work better
![grafik](https://user-images.githubusercontent.com/61663141/158943422-7eabe482-758e-4a80-8688-b47a690ccb1c.png)

**Comment by traverseda** [comment]
Yeah, I don't think Bungee would be a good choice for that. Maybe something "ubuntu"-ish?

**Comment by leogott** [comment]
without a font:
![Icon new export](https://user-images.githubusercontent.com/61663141/159123985-d5fcf87e-f15d-4927-8c1d-004573246361.svg)

**Comment by drwhut** [comment]
I have made a separate issue for the splash screen, since I have just added a logo and icon to the game :smile:
