### ISSUE TITLE
Add background images to the loading screen.

### ISSUE THREAD

**Issue by drwhut** [drwhut/tabletop-club#52]
**Is your feature request related to a problem? Please describe.**
The loading screen's background is completely blank.

**Describe the solution you'd like**
It would be really, really awesome if there was something cool to look at during the loading screen! If you have made, or have found, images that you think would look good in the background of the loading screen, please don't hesitate to post a comment on this issue! Make sure to include as much information as possible about the image, see [this page](https://opentabletop.readthedocs.io/en/latest/general/contributing/ways_to_contribute.html#proposing-assets) for what details you need to provide.

For example, the image could be a screenshot from the game (press `F9` to hide the UI, then press `F12` to take a screenshot), or it could even be artwork!

Keep in mind that the image should be landscape, and it should be at least 1080p.

**Describe alternatives you've considered**
None.

**Additional context**
For reference, this is what the loading screen currently looks like:
![Screenshot from 2021-03-25 19-24-56](https://user-images.githubusercontent.com/13645454/112531871-039f7e00-8da0-11eb-9126-d0e757996792.png)

**Comment by SeanKuehl** [comment]
Hey drwhut, I have found some images I'd like to suggest for the loading screen. The "this page" link for the details I have to provide is down for me at the moment, but I'll try to put in as much as possible.

Link to first image: https://pixabay.com/photos/dice-games-game-random-probability-5432439/
author: Mitaukano
license: pixabay license(https://pixabay.com/service/license/)
image type: jpg
notes: not landscape, it's a DND related picture and I feel it might fit with a tabletop game

link to second image: https://pixabay.com/photos/checkmate-chess-board-chess-board-1511866/
author: stevepb
license: pixabay license(https://pixabay.com/service/license/)
image type: jpg
notes: might be landscape, it's a chess related picture

these are just some suggestions, let me know if you need something different

**Comment by drwhut** [comment]
Hey! Thank you for the suggestions, but unfortunately, the Pixabay License includes the following clause that means we cannot include the images in our source code, which would come under redistribution:

> Don't redistribute or sell someone else's Pixabay images or videos on other stock or wallpaper platforms.

However, the images you linked looked really cool! If you are able to find similar images with more open licenses (e.g. the [CC BY-SA 4.0 License](https://creativecommons.org/licenses/by-sa/4.0/)), then I would happily consider putting them into the game!

**Comment by SeanKuehl** [comment]
Hey, I found some similar images under a license that allows (re)distribution, so license shouldn't be a problem. 

image link: https://search.creativecommons.org/photos/788355c8-133c-49cf-8654-71cf9f0499a0
author:  romainguy 
license: CC0
image type: JPEG
notes: 1024 × 683, chess image

image link: https://search.creativecommons.org/photos/619d6ad3-d8e5-4d81-8d44-6f956d225435
author: Grizzlybear.se 
license: CC0
image type: JPEG
notes: 1024 × 681 pixels, dice image

Let me know if these images are good to go into the game, whether or not you would need more or other details.

**Comment by drwhut** [comment]
Thank you! I really like that chess image, my only concern is that it may be a bit too small (compared to 1080p).

Slight tangent, but I had no idea that Creative Commons had a search function like that!

**Comment by SeanKuehl** [comment]
I have resized both images to 1920x1080, here are the results:
![chess](https://user-images.githubusercontent.com/71566798/121780157-19d20480-cb6d-11eb-94d5-ff723d4c50b4.jpeg)
![dice](https://user-images.githubusercontent.com/71566798/121780159-1b9bc800-cb6d-11eb-94b1-a95468a4f87c.jpeg)

If you like the results I can make a commit that adds them to the loading screen. 

P.S. yeah, creative commons has a search ability but just a heads up, when I searched up "dice" filtering for CC0 license I got a lot of odd non dice pictures first. It may still be a good resource for future resources.

**Comment by SeanKuehl** [comment]
I found another image that should meet all the criteria.

image link: https://unsplash.com/photos/nEbMedmVwgw
author: Hassan Pasha
dimensions: 5424 × 3588
license: https://unsplash.com/license
note: chess image

**Comment by drwhut** [comment]
Wow, that is a very high-res image! The license looks good as well. If anything, we should probably downscale it when putting it in the game, since not a lot of people will be able to view it at that level of detail, and it saves on space. Good find!

**Comment by SeanKuehl** [comment]
I'm glad you like it. Would you like me to try and get more images and if so how many more? Also when the image(s) are added to the game would you be doing commit or would I? I only ask because I'd need to know how to scale images with Godot to make the commit.

**Comment by drwhut** [comment]
If you're up to finding more images, go for it! My initial thought was to have around 5-6 images, but the more the better.

Don't worry about the commit, I've already got an idea as to how to implement the images into the loading screen. This issue was more about finding the images themselves, which you've helped with a lot!

**Comment by SeanKuehl** [comment]
Ok, here are some more images from Unsplash, let me know what you think.
image link: https://unsplash.com/photos/QuP5RL_E5oE
note: d6 dice

image link: https://unsplash.com/photos/bRqsXcEcKFw 
note: poker

image link: https://unsplash.com/photos/Y_bpePELbPo 
note: cribbage

image link: https://unsplash.com/photos/DC-UrroFRr4 
note: checkers

image link: https://unsplash.com/photos/nxizznysgXI 
note: mahjong

**Comment by drwhut** [comment]
Apologies for the incredibly long delay on a response - I've thought about what images to include for the loading screens, and personally I am now leaning more towards only including original images, e.g. screenshots taken from the game, or original artwork made for the game.

Since I am currently preparing for the first release of the game, I have plans to create a set of screenshots to be used as promotional material - which I may also include in the loading screens.

However, if anyone does want to make artwork or create screenshots to be used in the loading screens, please do not hesitate to comment (even if the issue has been closed in the future)!
