### ISSUE TITLE
New project name suggestions.

### ISSUE THREAD

**Issue by drwhut** [drwhut/tabletop-club#59]
I have been asked to rename this project, so this issue is for anyone to suggest a new name for the project!

**Comment by SeanKuehl** [comment]
here are some ideas: libre table top, free table top, board game maker, table top maker, imagination, creativity, imagination/creativity table top, table top creator/maker, new dawn table top.

**Comment by Rundik** [comment]
tablotopy, libretop, table-flip, distant-tabletop, remotetop, flextop

**Comment by drwhut** [comment]
The project has been renamed! Thank you for your suggestions :smile:
