### ISSUE TITLE
Add a notification system.

### ISSUE THREAD

**Issue by drwhut** [drwhut/tabletop-club#61]
**Is your feature request related to a problem? Please describe.**
Currently, the player isn't notified when certain events occur in-game. For example, when an autosave is made, or a screenshot is taken.

**Describe the solution you'd like**
When certain events occur, have a notification pop-up at the bottom of the screen. If there are multiple pop-ups, it should only display the last notification, and there should be an option to display the other notifications. The notifications should be able to be cleared, either individually or altogether.

**Describe alternatives you've considered**
None

**Additional context**
Notifications can also appear when warnings and errors are thrown by the engine, thanks to [this commit](https://github.com/drwhut/tabletop_club_godot_module/commit/1ba871b3ca8d079ca86e734534cd7cd32951b8be) in the custom module.

**Comment by traverseda** [comment]
Have you considered expanding the chat feature and adding a system console tab?

**Comment by drwhut** [comment]
That's a good point actually, there is already a message box in the game for multiplayer (and it already says when players leave and join the game). I'll consider putting the notifications in that box for now, but keeping the API vague enough to allow for an expansion of the feature later on.
